// <auto-generated />
using System;
using AutoServiceShop.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoServiceShop.Migrations
{
    [DbContext(typeof(AutoServiceDbContext))]
    partial class AutoServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("AutoServiceShop.DataAccess.EfCore.Entities.EfCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("AutoServiceShop.DataAccess.EfCore.Entities.EfOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerName");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("OrderDate");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("AutoServiceShop.DataAccess.EfCore.Entities.EfProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("Color");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("Country");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<double>("Discount")
                        .HasColumnType("REAL")
                        .HasColumnName("Discount");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FullName");

                    b.Property<string>("ImagePaths")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImagePaths");

                    b.Property<bool>("InStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InStock");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT")
                        .HasColumnName("Manufacturer");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("Rating");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ShortName");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT")
                        .HasColumnName("Size");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("AutoServiceShop.DataAccess.EfCore.Entities.EfOrder", b =>
                {
                    b.HasOne("AutoServiceShop.DataAccess.EfCore.Entities.EfProduct", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoServiceShop.DataAccess.EfCore.Entities.EfProduct", b =>
                {
                    b.HasOne("AutoServiceShop.DataAccess.EfCore.Entities.EfCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoServiceShop.DataAccess.EfCore.Entities.EfCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoServiceShop.DataAccess.EfCore.Entities.EfProduct", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
